name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install flake8
      - name: Set up database
        env:
          DJANGO_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          python3 manage.py makemigrations
          python3 manage.py migrate
      - name: Code Linting
        run: |
          python3 -m flake8 manage.py
      - name: Run Django tests
        env:
          DJANGO_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          python3 manage.py test

