name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Deploy to Heroku
        if: job.status == 'success'
        run: |
          git remote add heroku  https://heroku:${{ secrets.HEROKU_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_APP }}.git
          git push heroku HEAD:master -f